name=SimpleFOCDrivers_Calibrated
version=1.0.9
author=Simplefoc
sentence=CalibratedSensor from Arduino-FOC-drivers v1.0.9
paragraph=Encoder autocalibration (Ben Katz method) for SimpleFOC. Local copy of CalibratedSensor only.
category=Device Control
url=https://github.com/simplefoc/Arduino-FOC-drivers
architectures=*
depends=Simple FOC
